### PR TITLE
Tab Clean Up

### PR DESCRIPTION
**Pull request by anh65498**
+ Changes as suggested in the Issue

### CODE REVIEW

**Comment by anh65498** [comment]
Not sure why I am failing Netlify when I run `yarn start` without error. The Chrome console does have 3 warnings `findDOMNode is deprecated in StrictMode`

**Comment by therexone** [comment]
Check out the logs
image

**Comment by anh65498** [comment]
This is unfortunate but here's the warning in Chrome console

I deduct from the console that the error is caused by devextreme-reactive's Grid. Unfortunately, the devextreme-reactive is still working on this problem (as seen in this issue https://github.com/DevExpress/devextreme-reactive/issues/2727)

**Comment by therexone** [comment]
The devextreme grid's warnings have always been there and it never failed in CI because its not causing the build to fail.
What's causing the netlify CI to fail are these two eslint warnings 
image
Fix these up and the netlify deploy will be good to go

**Comment by randomlylelo** [comment]
The dark mode stuff should have been moved last time. I think you have not kept your branch up to date.
Try `git pull upstream master`
and then fix all the conflicts
then `git push`

**Comment by randomlylelo** [comment]
Oh wait I take that back. Lemme check again.

**Comment by randomlylelo** [comment]
Quick question: on commit `6f3ce3a` "Merge branch 'master' into feature/edit-tab-names" did u modify the files before pushing the merge? As in after you did `git pull upstream master` you modified some files and then you went `git push`. I'm asking because I notice that the `Settings` tab code was never added to your commit which is what caused eslint to error in netlify.

Overall the PR looks good except the removal of Settings Tab & Darkmode. Could you please add it back in?

**Comment by anh65498** [comment]
Yes, I modified the files before merging and pushing the merge. I couldn't get the Settings tab from master even though I did `git pull origin feature/edit-tab-names` and `git pull upstream feature/edit-tab-names`. I removed the dark mode because there's an issue about that. Sorry.

**Comment by anh65498** [comment]
Thank you 😅 Do you merge or do I merge?

**Pull request merged**
